### ISSUE TITLE
Перевести сбор статистики с todo-пунктов на импорт

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-diary#101]
- [x] #102 &mdash; статистика ежедневных todo-пунктов;
- [x] #103 &mdash; статистика проектов;
- [x] #104 &mdash; список проектов.
