### ISSUE TITLE
Убрать поддержку флагов у todo-пунктов

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-diary#105]
- [x] todo-пункты:
    - [x] хранение флагов в БД;
    - [x] отображение флагов;
    - [x] редактирование флагов;
    - [x] экспорт флагов при бекапе;
    - [x] восстановление флагов из бекапа;
- [x] ежедневные todo-пункты:
    - [x] хранение флагов в БД;
    - [x] отображение флагов;
    - [x] редактирование флагов;
    - [x] экспорт флагов при бекапе;
    - [x] восстановление флагов из бекапа.
