### ISSUE TITLE
Изменить политику относительно точек с запятой в todo-пунктах

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-diary#106]
- [x] todo-пункты:
    - [x] убрать автоматическое добавление точек с запятой в конце todo-пунктов;
    - [x] добавить автоматическое удаление точек с запятой в конце todo-пунктов;
- [x] ежедневные todo-пункты:
    - [x] убрать автоматическое добавление точек с запятой в конце todo-пунктов;
    - [x] добавить автоматическое удаление точек с запятой в конце todo-пунктов.
