### ISSUE TITLE
Удалить возможность редактирования todo-пунктов

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-diary#107]
Удалить:

- [x] добавление todo-пунктов;
- [x] редактирование порядка todo-пунктов;
- [x] редактирование текста todo-пунктов;
- [x] перенос todo-пунктов на день назад;
- [x] удаление todo-пунктов.
