### ISSUE TITLE
Изменить способ отображения списка todo-пунктов

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-diary#108]
- [x] на главной странице отображать список дат всех todo-пунктов (с пагинацией);
- [x] для каждой даты по запросу отображать список принадлежащих ей todo-пунктов (без пагинации);
- [x] удалить параметр &laquo;Число пунктов на странице&raquo; из параметров.
