### ISSUE TITLE
Incorrect running time of the "AddDailyPoints" command 

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-diary#266]
The last time this command was run at 2022-06-27 03:50:57.

- [x] ~~Check time zones in the containers~~ (`date +"%Z %z"`):
  - [x] ~~in the main container~~ (`UTC +0000`);
  - [x] ~~in the container with the MySQL database~~ (`UTC +0000`);
  - [x] ~~in the container with the ofelia tool~~ (`UTC +0000`).
- [x] ~~Fix time zones in the containers~~:
  - [x] ~~in the main container~~ (moved to #267);
  - [x] ~~in the container with the MySQL database~~ (moved to #268);
  - [x] ~~in the container with the ofelia tool~~ (moved to #272).
- [x] ~~Check that command running time is set absolutely, not relatively, in the container with the ofelia tool.~~
- [ ] Set command running time absolutely, instead of relatively, in the container with the ofelia tool.
