### ISSUE TITLE
Добавить статистику todo-пунктов

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-diary#74]
Статистика должна состоять из:

- [x] #80 &mdash; статистики ежедневных todo-пунктов;
- [x] #81 &mdash; статистики проектов;
- [x] #79 &mdash; дерево todo-пунктов.
